# Generated by GitHub Copilot
# Azure Landing Zone Output values with descriptions and sensitive flags

# Resource Group Outputs
output "management_resource_group_name" {
  description = "The name of the management resource group"
  value       = azurerm_resource_group.management.name
}

output "connectivity_resource_group_name" {
  description = "The name of the connectivity resource group"
  value       = azurerm_resource_group.connectivity.name
}

output "shared_services_resource_group_name" {
  description = "The name of the shared services resource group"
  value       = azurerm_resource_group.shared_services.name
}

# Networking Outputs
output "hub_virtual_network_id" {
  description = "The ID of the hub virtual network"
  value       = azurerm_virtual_network.hub.id
}

output "hub_virtual_network_name" {
  description = "The name of the hub virtual network"
  value       = azurerm_virtual_network.hub.name
}

output "gateway_subnet_id" {
  description = "The ID of the gateway subnet"
  value       = azurerm_subnet.gateway.id
}

output "management_subnet_id" {
  description = "The ID of the management subnet"
  value       = azurerm_subnet.management.id
}

# Security and Monitoring Outputs
output "log_analytics_workspace_id" {
  description = "The ID of the Log Analytics workspace"
  value       = azurerm_log_analytics_workspace.main.id
}

output "log_analytics_workspace_name" {
  description = "The name of the Log Analytics workspace"
  value       = azurerm_log_analytics_workspace.main.name
}

output "key_vault_id" {
  description = "The ID of the Key Vault"
  value       = azurerm_key_vault.main.id
}

output "key_vault_uri" {
  description = "The URI of the Key Vault"
  value       = azurerm_key_vault.main.vault_uri
  sensitive   = true
}

# Azure Firewall Outputs (conditional)
output "azure_firewall_id" {
  description = "The ID of the Azure Firewall (if enabled)"
  value       = var.enable_azure_firewall ? azurerm_firewall.main[0].id : null
}

output "azure_firewall_private_ip" {
  description = "The private IP address of the Azure Firewall (if enabled)"
  value       = var.enable_azure_firewall ? azurerm_firewall.main[0].ip_configuration[0].private_ip_address : null
}

# Azure Bastion Outputs (conditional)
output "bastion_host_id" {
  description = "The ID of the Azure Bastion host (if enabled)"
  value       = var.enable_bastion ? azurerm_bastion_host.main[0].id : null
}

output "bastion_host_fqdn" {
  description = "The FQDN of the Azure Bastion host (if enabled)"
  value       = var.enable_bastion ? azurerm_bastion_host.main[0].dns_name : null
}

# VPN Gateway Outputs (conditional)
output "vpn_gateway_id" {
  description = "The ID of the VPN Gateway (if enabled)"
  value       = var.enable_vpn_gateway ? azurerm_virtual_network_gateway.vpn[0].id : null
}

# Environment Information
output "environment" {
  description = "The deployment environment"
  value       = var.environment
}

output "location" {
  description = "The Azure region where resources are deployed"
  value       = var.location
}
