# Generated by GitHub Copilot
# Azure Landing Zone Variables - All configurable parameters

# General Configuration
variable "environment" {
  type        = string
  description = "Environment name (dev, test, prod)"
  default     = "dev"
  
  validation {
    condition     = contains(["dev", "test", "prod"], var.environment)
    error_message = "Environment must be dev, test, or prod."
  }
}

variable "location" {
  type        = string
  description = "Primary Azure region for resources"
  default     = "East US"
}

variable "location_secondary" {
  type        = string
  description = "Secondary Azure region for disaster recovery"
  default     = "West US 2"
}

variable "organization_name" {
  type        = string
  description = "Organization name for naming convention"
  default     = "contoso"
}

# Network Configuration
variable "hub_vnet_address_space" {
  type        = list(string)
  description = "Address space for the hub virtual network"
  default     = ["10.0.0.0/16"]
}

variable "gateway_subnet_address_prefix" {
  type        = string
  description = "Address prefix for the gateway subnet"
  default     = "10.0.0.0/27"
}

variable "firewall_subnet_address_prefix" {
  type        = string
  description = "Address prefix for Azure Firewall subnet"
  default     = "10.0.1.0/26"
}

variable "bastion_subnet_address_prefix" {
  type        = string
  description = "Address prefix for Azure Bastion subnet"
  default     = "10.0.2.0/27"
}

variable "management_subnet_address_prefix" {
  type        = string
  description = "Address prefix for management subnet"
  default     = "10.0.3.0/24"
}

# Tags
variable "default_tags" {
  type        = map(string)
  description = "Default tags to be applied to all resources"
  default = {
    Environment  = "dev"
    Owner        = "platform-team"
    CostCenter   = "IT-001"
    Project      = "landing-zone"
    Criticality  = "mission-critical"
  }
}

# Security Configuration
variable "enable_azure_firewall" {
  type        = bool
  description = "Enable Azure Firewall deployment"
  default     = true
}

variable "enable_bastion" {
  type        = bool
  description = "Enable Azure Bastion deployment"
  default     = true
}

variable "enable_vpn_gateway" {
  type        = bool
  description = "Enable VPN Gateway deployment"
  default     = false
}

variable "vpn_gateway_sku" {
  type        = string
  description = "SKU for VPN Gateway"
  default     = "VpnGw1"
  
  validation {
    condition     = contains(["VpnGw1", "VpnGw2", "VpnGw3", "VpnGw1AZ", "VpnGw2AZ", "VpnGw3AZ"], var.vpn_gateway_sku)
    error_message = "VPN Gateway SKU must be a valid Azure VPN Gateway SKU."
  }
}

# Monitoring Configuration
variable "log_analytics_retention_days" {
  type        = number
  description = "Log Analytics workspace retention in days"
  default     = 30
  
  validation {
    condition     = var.log_analytics_retention_days >= 30 && var.log_analytics_retention_days <= 730
    error_message = "Log Analytics retention must be between 30 and 730 days."
  }
}

variable "enable_security_center" {
  type        = bool
  description = "Enable Azure Security Center/Defender"
  default     = true
}
